Models/Vendor.cs
using System.Collections.Generic;

namespace Sammishop.Models
{
    public class Vendor : InfoBase
    {
        public virtual List<Product> Products { get; set; }
    }
}

ViewModels/VendorView.cs
namespace  Sammishop.ViewModels
{
    public class VendorView
    {
        public string Name { get; set; }

        public string Address { get; set; }

        public string Email { get; set; }

        public string Phone { get; set; }

        public bool Active { get; set; }
    }
}

Controllers/VendorsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Sammishop.Data;
using Sammishop.Mapper;
using Sammishop.Models;
using Sammishop.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace  Sammishop.Controllers
{
    [Route("admin/vendor")]
    public class VendorsController : Controller
    {
        private readonly DataContext _context;

        public VendorsController(DataContext context)
        {
            _context = context;
        }

        // GET: ProductCategories
        [HttpGet, Route("categories")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Vendors.ToListAsync());
        }

        [HttpGet, Route("update/status/{id}")]
        public async Task<IActionResult> UpdateStatus(int? id)
        {
            var vendor = _context.Vendors.Find(id);
            if (vendor == null)
            {
                return NotFound();
            }
            vendor.Active = !vendor.Active;
            _context.Entry(vendor).State = EntityState.Modified;
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET: ProductCategories/Create
        [HttpGet, Route("create")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: ProductCategories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.

        [HttpPost, Route("create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(VendorView vendorView)
        {
            Vendor vendor = new Vendor();
            vendor.Map(vendorView);
            if (ModelState.IsValid)
            {
                _context.Add(vendor);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(vendor);
        }

        // GET: ProductCategories/Edit/5
        [HttpGet, Route("edit/{id}")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vendor = await _context.Vendors.FindAsync(id);
            if (vendor == null)
            {
                return NotFound();
            }
            return View(vendor);
        }

        // POST: ProductCategories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [ValidateAntiForgeryToken]
        [HttpPost, Route("edit/{id}")]
        public async Task<IActionResult> Edit(int id, VendorView vendorView)
        {
            var vendor = _context.Vendors.Find(id);

            if (vendor == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    vendor.Map(vendorView);
                    _context.Update(vendor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VendorExists(vendor.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(vendor);
        }

        // GET: ProductCategories/Delete/5
        [HttpGet, Route("delete/{id}")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vendor = await _context.Vendors
                .FirstOrDefaultAsync(m => m.Id == id);
            if (vendor != null)
            {
                _context.Vendors.Remove(vendor);
                await _context.SaveChangesAsync();

            }
            return RedirectToAction(nameof(Index));
        }

        private bool VendorExists(int id)
        {
            return _context.Vendors.Any(e => e.Id == id);
        }

        [HttpGet, Route("search")]
        public async Task<IActionResult> Search([FromQuery]string query)
        {
            var dataContext = _context.Vendors.ToList();
            var vendor = new List<Vendor>();

            if (!String.IsNullOrEmpty(query))
            {
                foreach (var item in dataContext)
                {
                    if (item.Name.ToLower().Contains(query.ToLower()))
                    {
                        vendor.Add(item);
                    }
                }
            }
            return vendor.Count == 0 ? View("index", dataContext) : View("index", vendor);
        }
    }
}

Views/Vendors/Create.cshtml
@model Sammishop.Models.Vendor

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<div class="sb2-2">
    <div class="sb2-2-2">
        <ul>
            <li>
                <a href="#"><i class="fa fa-home" aria-hidden="true"></i> Home</a>
            </li>
            <li class="active-bre">
                <a href="#"> Edit Listing</a>
            </li>
        </ul>
    </div>
    <div class="sb2-2-add-blog sb2-2-1">
        <h2>Thêm mới</h2>
        <p></p>
        <p></p>
        <div class="tab-content">
            <div id="home" class="tab-pane fade in active">
                <div class="box-inn-sp">
                    @*<div class="inn-title">
                            <h4>Listing Information</h4>
                            <p>Airtport Hotels The Right Way To Start A Short Break Holiday</p>
                        </div>*@
                    <div class="bor">
                        <form asp-action="Create" enctype="multipart/form-data">
                            @*Bên trái*@
                            <div class="col s12">
                                <div class="row">
                                    <div class="input-field col s12 tensp">
                                        <input id="product-name" type="text" class="validate" asp-for="Name">
                                        <label>Tên nhà cung cấp</label>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="input-field col s12 tensp">
                                        <input id="phone-number" type="text" class="validate " asp-for="Phone">
                                        <label>Số điện thoại</label>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="input-field col s12 tensp">
                                        <input id="product-name" type="text" class="validate" asp-for="Email">
                                        <label>Email</label>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="input-field col s12 tensp">
                                        <input id="product-name" type="text" class="validate" asp-for="Address">
                                        <label>Địa chỉ</label>
                                    </div>
                                </div>
                                <div class="row test">
                                    <div class="col s12">
                                        <input type="checkbox" class="filled-in" id="filled-in-box-3" asp-for="Active" />
                                        <label for="filled-in-box-3">Xuất bản</label>
                                    </div>
                                </div>

                            </div>

                            <div class="col s8">
                                <div class="row">
                                    <div class="input-field col s8">
                                        <button type="submit" class="btn btn-primary btn-sm">
                                            <i class="fa fa-save"> </i> Lưu[Cập nhật]
                                        </button>
                                        <a asp-action="Index">
                                            <button type="button" class="btn btn-primary btn-sm">
                                                <i class="fa fa-times-circle "></i> Thoát
                                            </button>
                                        </a>
                                        @*<input type="submit" class="waves-effect waves-light btn-large " value="Submit">*@
                                    </div>
                                </div>
                            </div>

                            <div style="clear: both"></div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Vendors/Delete.cshtml
@model Sammishop.Models.Vendor

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Vendor</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ModifiedBy)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ModifiedBy)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Active)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Active)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ModifiedAt)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ModifiedAt)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Vendors/Edit.cshtml
@model Sammishop.Models.Vendor

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<div class="sb2-2">
    <div class="sb2-2-2">
        <ul>
            <li>
                <a href="#"><i class="fa fa-home" aria-hidden="true"></i> Home</a>
            </li>
            <li class="active-bre">
                <a href="#"> Edit Listing</a>
            </li>
        </ul>
    </div>
    <div class="sb2-2-add-blog sb2-2-1">
        <h2>Thêm mới</h2>
        <p></p>
        <p></p>
        <div class="tab-content">
            <div id="home" class="tab-pane fade in active">
                <div class="box-inn-sp">
                    @*<div class="inn-title">
                            <h4>Listing Information</h4>
                            <p>Airtport Hotels The Right Way To Start A Short Break Holiday</p>
                        </div>*@
                    <div class="bor">
                        <form asp-action="Edit" enctype="multipart/form-data">
                            @*Bên trái*@
                            <div class="col s12">
                                <div class="row">
                                    <div class="input-field col s12 tensp">
                                        <input id="product-name" type="text" class="validate" asp-for="Name">
                                        <label>Tên nhà cung cấp</label>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="input-field col s12 tensp">
                                        <input id="phone-number" type="text" class="validate " asp-for="Phone">
                                        <label>Số điện thoại</label>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="input-field col s12 tensp">
                                        <input id="product-name" type="text" class="validate" asp-for="Email">
                                        <label>Email</label>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="input-field col s12 tensp">
                                        <input id="product-name" type="text" class="validate" asp-for="Address">
                                        <label>Địa chỉ</label>
                                    </div>
                                </div>
                                <div class="row test">
                                    <div class="col s12">
                                        <input type="checkbox" class="filled-in" id="filled-in-box-3" asp-for="Active" />
                                        <label for="filled-in-box-3">Xuất bản</label>
                                    </div>
                                </div>

                            </div>

                            <div class="col s8">
                                <div class="row">
                                    <div class="input-field col s8">
                                        <button type="submit" class="btn btn-primary btn-sm">
                                            <i class="fa fa-save"> </i> Lưu[Cập nhật]
                                        </button>
                                        <a asp-action="Index">
                                            <button type="button" class="btn btn-primary btn-sm">
                                                <i class="fa fa-times-circle "></i> Thoát
                                            </button>
                                        </a>
                                        @*<input type="submit" class="waves-effect waves-light btn-large " value="Submit">*@
                                    </div>
                                </div>
                            </div>

                            <div style="clear: both"></div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Vendors/Index.cshtml
@model IEnumerable<Sammishop.Models.Vendor>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<h2>Index</h2>

<div class="sb2-2">
    <div class="sb2-2-2">
        <ul>
            <li>
                <a href="#"><i class="fa fa-home" aria-hidden="true"></i> Trang chủ</a>
            </li>
            <li class="active-bre">
                <a href="#"> Nhà cung cấp</a>
            </li>
        </ul>
    </div>
    <div class="sb2-2-3">
        <div class="row">
            <div class="col-md-12">
                <div class="box-inn-sp">
                    <div class="inn-title">
                        <h4><i class="fa fa-bookmark"></i> Danh sách nhà cung cấp</h4>
                        <a class="dropdown-button drop-down-meta" href="#" data-activates="dr-users"><i class="material-icons">more_vert</i></a>
                        <ul id="dr-users" class="dropdown-content">
                            <li>
                                <a asp-action="Create">Thêm mới</a>
                            </li>
                            <li>
                                <a href="#!">Sửa</a>
                            </li>
                            <li>
                                <a href="#!">Cập nhật</a>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <a href="#!"><i class="material-icons">delete</i>Xóa</a>
                            </li>
                            <li>
                                <a asp-action="Index"><i class="material-icons">subject</i>View All</a>
                            </li>
                        </ul>

                        <!-- Dropdown Structure -->

                    </div>
                    <div class="inn-title row">
                        <div class="timkiem col-md-1">
                            <label>Tìm kiếm</label>
                        </div>
                        <form class="app-search col-md-3" asp-controller="Vendors" asp-action="Search" method="get">
                            <input type="text" placeholder="Search..." class="form-control" name="query">
                            <button type="submit" class="search-submit"><i class="fa fa-search"></i></button>
                        </form>
                    </div>
                    <div class="tab-inn">
                        <div class="table-responsive table-desi">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th class="text-center">STT</th>
                                        <th>Tên nhà cung cấp</th>
                                        <th>Số điện thoại</th>
                                        <th>Email</th>
                                        <th>Địa chỉ</th>
                                        <th class="text-center">Trạng thái</th>
                                        <th class="text-center">Sửa</th>
                                        <th class="text-center">Xóa</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @{ var i = 1;}
                                    @foreach (var item in Model)
                                    {
                                    <tr>
                                        <td class="text-center">
                                            <span class="list-img">@(i++)</span>
                                        </td>

                                        <td>
                                            <span class="list-img">@Html.DisplayFor(modelItem => item.Name)</span>
                                        </td>

                                        <td>
                                            <span class="list-img">@Html.DisplayFor(modelItem => item.Phone)</span>
                                        </td>

                                        <td>
                                            <span class="list-img">@Html.DisplayFor(modelItem => item.Email)</span>
                                        </td>

                                        <td>
                                            <span class="list-img">@Html.DisplayFor(modelItem => item.Address)</span>
                                        </td>

                                        <td class="text-center">
                                            <a asp-action="UpdateStatus" asp-route-id="@item.Id"> <i class="@(@item.Active == true ? "fa fa-check-circle" : "fa fa-ban red")"></i></a>

                                        </td>
                                        @*<td>
            <span class="list-img">@item.Price.ToString("#,### VNĐ")</span>
        </td>
        <td>
            <span class="list-img">@item.CreatedAt.ToString("dd/MM/yyyy")</span>
        </td>*@

                                        <td class="text-center">
                                            <a asp-action="Edit" asp-route-id="@item.Id"><i class="fa fa-pencil-square-o" aria-hidden="true"> Sửa</i></a>
                                        </td>
                                        <td class="text-center">

                                            <a asp-action="Delete" asp-route-id="@item.Id" onclick="return confirm('Bạn có chắc chắn muốn xóa sản phẩm này không?');"><i class="fa fa-trash-o red"> Xóa</i></a>
                                        </td>


                                    </tr>
                                    }


                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>